// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using POMHomework.WebServices;
//
//    var wishlist = Wishlist.FromJson(jsonString);

namespace POMHomework.WebServices
{
    using Newtonsoft.Json;

    public partial class Wishlist
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("books")]
        public Book[] Books { get; set; }
    }

  

    public partial class Wishlist
    {
        public static Wishlist FromJson(string json) => JsonConvert.DeserializeObject<Wishlist>(json, POMHomework.WebServices.Converter.Settings);
    }

 

}
